<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-08-20T13:05:10Z" name="Suite" finished-at="2019-08-20T13:07:22Z" duration-ms="132228">
    <groups>
    </groups>
    <test started-at="2019-08-20T13:05:10Z" name="Test_0" finished-at="2019-08-20T13:07:22Z" duration-ms="132228">
      <class name="com.project1.testscripts.TestCase1">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:com.project1.testscripts.TestCase1@349c1daf]" started-at="2019-08-20T18:34:25Z" name="beforeSuite" finished-at="2019-08-20T18:34:57Z" duration-ms="31842" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method signature="test1(java.lang.String)[pri:0, instance:com.project1.testscripts.TestCase1@349c1daf]" started-at="2019-08-20T18:35:11Z" name="test1" finished-at="2019-08-20T18:37:11Z" duration-ms="120093" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[PocTest1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.wma.framework.common.WebDriverFactory.createInstance(WebDriverFactory.java:139)
	at com.wma.framework.common.WebDriverFactory.getWebDriver(WebDriverFactory.java:158)
	at com.wma.framework.common.InitTest.getWebDriver(InitTest.java:64)
	at com.project1.testscripts.TestCase1.test1(TestCase1.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.wma.framework.driver.DriverScript.startExecution(DriverScript.java:106)
	at com.project1.driver.Project1Driver.main(Project1Driver.java:10)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="afterSuit()[pri:0, instance:com.project1.testscripts.TestCase1@349c1daf]" started-at="2019-08-20T18:37:22Z" name="afterSuit" finished-at="2019-08-20T18:37:22Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuit -->
      </class> <!-- com.project1.testscripts.TestCase1 -->
    </test> <!-- Test_0 -->
  </suite> <!-- Suite -->
</testng-results>
